steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/team-nan-9620011412001/github.com/mirzaazwad/test-app:$SHORT_SHA', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/team-nan-9620011412001/github.com/mirzaazwad/test-app:$SHORT_SHA']